// Copyright Kani Contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT
import * as vscode from 'vscode';

import { SourceCodeParser } from './sourceCodeParser';

/**
 * CodelensProvider
 */
export class CodelensProvider implements vscode.CodeLensProvider {
	private codeLenses: vscode.CodeLens[] = [];
	private regex: RegExp;
	private _onDidChangeCodeLenses: vscode.EventEmitter<void> = new vscode.EventEmitter<void>();
	public readonly onDidChangeCodeLenses: vscode.Event<void> = this._onDidChangeCodeLenses.event;

	constructor() {
		this.regex = /kani_concrete_playback/g;

		vscode.workspace.onDidChangeConfiguration((_) => {
			this._onDidChangeCodeLenses.fire();
		});
	}

	/**
	 * Extends the provideCodeLenses function provided by CodeLens and adds Kani generated unit tests to their lists
	 *
	 * @param document - Takes in the current file and provides the codelens button
	 * @param _token - Unused token
	 * @returns
	 */

	public async provideCodeLenses(
		document: vscode.TextDocument,
		_token: vscode.CancellationToken,
	): Promise<any> {
		if (vscode.workspace.getConfiguration('codelens-kani').get('enableCodeLens', true)) {
			this.codeLenses = [];
			const text = document.getText();

			// Find the unit tests by searching for its text
			const kani_concrete_tests = await SourceCodeParser.extractKaniTestMetadata(text);

			for (const item of kani_concrete_tests) {
				const function_item_name = item.at(0);

				if (function_item_name === undefined) {
					continue;
				}

				const startPosition = item.at(1);

				// This is the metadata that VSCode needs to place the codelens button
				const line = document.lineAt(startPosition.row);
				const indexOf = line.text.indexOf(function_item_name);
				const position = new vscode.Position(line.lineNumber, indexOf);
				const range = document.getWordRangeAtPosition(position, new RegExp(this.regex));

				const runTestAction = {
					title: '$(play) Run Test (Kani)',
					tooltip: 'Run unit test generated by Kani',
					command: 'codelens-kani.codelensAction',
					arguments: [function_item_name],
				};

				const debugTestAction = {
					title: '$(debug) Debug Harness (Kani)',
					tooltip: 'Debug unit test generated by Kani',
					command: 'extension.connectToDebugger',
					arguments: [function_item_name],
				};

				if (range) {
					const runTestCodelens = new vscode.CodeLens(range, runTestAction);
					const debugTestCodelens = new vscode.CodeLens(range, debugTestAction);

					this.codeLenses.push(runTestCodelens);
					this.codeLenses.push(debugTestCodelens);
				}
			}

			// The setting for the coverage code lens needs to be switched on for the mechanism
			// to be enabled
			if (vscode.workspace.getConfiguration('codelens-kani').get('highlightCoverage', true)) {
				// Retrieve harness metadata from the tree-sitter which will be used to place the
				// `Get coverage info` code lens button.
				const kani_harnesses = await SourceCodeParser.getAttributeFromRustFile(text);

				for (const harness of kani_harnesses) {
					const harness_name = harness.harnessName;

					// If the harness is empty or undefined, skip to the next iteration
					if (harness_name === undefined || harness_name === '') {
						continue;
					}

					const startPosition = harness.endPosition;

					// This is the metadata that VSCode needs to place the codelens button
					const line = document.lineAt(startPosition.row);
					const indexOf = line.text.indexOf(harness_name);
					const position = new vscode.Position(line.lineNumber, indexOf);
					const range = document.getWordRangeAtPosition(position);

					const codeCoverageAction = {
						title: '$(play) Get coverage info',
						tooltip: 'Highlight code with coverage information generated by Kani',
						command: 'codelens-kani.highlightCoverage',
						arguments: [harness_name],
					};

					if (range) {
						const codeCoverageCodelens = new vscode.CodeLens(range, codeCoverageAction);
						this.codeLenses.push(codeCoverageCodelens);
					}
				}
			}
			return this.codeLenses;
		}

		return [];
	}

	public resolveCodeLens(codeLens: vscode.CodeLens): vscode.ProviderResult<vscode.CodeLens> {
		return codeLens;
	}
}
